apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-service
  namespace: healix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: queue-service
  template:
    metadata:
      labels:
        app: queue-service
    spec:
      containers:
        - name: queue-service
          image: healix/queue-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: queue-service-config
