apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-service
  namespace: healix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital-service
  template:
    metadata:
      labels:
        app: hospital-service
    spec:
      containers:
        - name: hospital-service
          image: healix/hospital-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: hospital-service-config
