apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: healix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
        - name: audit-service
          image: healix/audit-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: audit-service-config
